language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.10"
install:
    - dzil authordeps --missing | cpanm
    - dzil listdeps --author --missing | cpanm

sudo: false

script:
    - dzil test --author --release
